# Generated by Django 4.0.2 on 2022-02-05 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunshine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sunbeam_1', models.TextField(blank=True, max_length=250, null=True, verbose_name='Sunbeam #1')),
                ('sunbeam_2', models.TextField(blank=True, max_length=250, null=True, verbose_name='Sunbeam #2')),
                ('sunbeam_3', models.TextField(blank=True, max_length=250, null=True, verbose_name='Sunbeam #3')),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
