# Generated by Django 4.0.2 on 2022-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apenv_dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
